In [8]:
import numpy as np
v1 = np.arange(10, 49)
print(v1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [13]:
m = np.array([[i + 3*j for i in range(3)] for j in range(3)])
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
import numpy as np
m3x3 = np.empty((3,3))
print(m3x3)

[[1.70751313e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [17]:
rand_arr = np.random.randint(0, 10, size=(10, 10))
print(rand_arr)

[[8 7 5 5 1 3 9 6 9 8]
 [5 0 5 9 5 2 3 7 9 4]
 [1 3 2 9 5 4 4 5 6 0]
 [1 2 6 9 6 1 9 6 6 4]
 [4 8 0 7 8 5 5 8 3 9]
 [0 6 4 7 3 3 4 1 0 2]
 [9 7 9 6 2 8 4 5 6 2]
 [3 2 7 2 7 8 0 2 0 4]
 [0 6 4 7 9 6 3 5 9 7]
 [6 3 1 8 2 7 9 9 7 7]]


In [18]:
print(np.max(rand_arr))
print(np.min(rand_arr))

9
0


In [19]:
rand_vec = np.random.randint(0, 30, size=(30))
print(rand_vec)

[24 20 12 25  8 17 20 18  6 17 22 28 25 19 10  4 22 28 24 27  9 27 24  7
 19 26 24 24  5  4]


In [ ]:
rand_vec.sort()
print(rand_vec.mean())

20


In [ ]:
a = np.random.randint(0, 100, size=(5,5))
norm = np.linalg.norm(a)
print(norm)

[[0.56701031 0.89690722 0.27835052 0.39175258 0.        ]
 [0.97938144 0.31958763 0.77319588 0.90721649 0.08247423]
 [0.97938144 0.73195876 0.43298969 0.39175258 0.91752577]
 [0.62886598 0.41237113 0.67010309 0.25773196 0.70103093]
 [0.83505155 1.         0.4742268  0.97938144 0.60824742]]


In [24]:
m5x3 = np.random.randint(1, 10, size=(5,3))
m3x2 = np.random.randint(1, 10, size=(3,2))
print(np.dot(m5x3, m3x2))

[[105 108]
 [ 85 127]
 [ 88 115]
 [ 79  94]
 [ 95 128]]


In [27]:
m3x3 = np.random.randint(1, 10, size=(3,3))
m3x3_2 = np.random.randint(1, 10, size=(3,3))
print(np.dot(m3x3, m3x3_2))

[[165  82  42]
 [157  80  41]
 [100  38  23]]


In [28]:
m4x4 = np.random.randint(1, 10, size=(4,4))
print(m4x4.transpose())

[[4 9 5 9]
 [1 2 5 4]
 [9 5 3 8]
 [9 9 2 9]]


In [29]:
detetminant = np.linalg.det(m3x3)
print(detetminant)

-29.99999999999999


In [30]:
A = np.random.randint(1, 10, size=(3,4))
B = np.random.randint(1, 10, size=(4, 3))
print(np.dot(A, B))

[[ 50  76  84]
 [ 76 110 134]
 [ 93 137 202]]


In [ ]:
m3 = np.random.randint(1, 10, size=(3))
print(np.dot(m3x3, m3.reshape(3,1)))

[[ 8 81  8]
 [ 7 81  8]
 [ 7 54  2]]


In [ ]:
A = np.array([
    [2, 4, 6],
])
b = np.array([2])
x = np.linalg.solve(A, b)
print(x)

[[1.         0.5        0.33333333]
 [0.16666667 0.14285714 0.125     ]
 [0.09090909 0.08333333 0.07692308]]


In [34]:
rowwise = np.sum(A, axis=1)
columnwise = np.sum(A, axis=0)
print(rowwise, columnwise)

[12 42 72] [36 42 48]
